### ISSUE TITLE
Heroku needs to be updated

### ISSUE THREAD

**Issue by lilyszhang** [Codenames-Online/back#17]

**Comment by vkoves** [comment]
The deploy is going up now! I've also setup Heroku to auto-deploy the `master` branch, so we shouldn't have any issues with this from here on. If anyone would like Heroku access, message me. I'll close this issue since the build has gone up.

**Comment by vkoves** [comment]
Reopening as Heroku is not working after the deploy

**Comment by vkoves** [comment]
Heroku is updated, and the [front-end site](https://codenames-online.github.io/front/) is working properly with it! Auto-deploy is also working as intended, so I'll close this issue.
